### ISSUE TITLE
Does this actually help with debugging?

### ISSUE THREAD

**Issue by dustinlacewell** [rush-lang/vscode-rush#8]
How?

**Comment by rtlayzell** [comment]
Unfortunately not, the language server hasn't been developed and integrated with the extension yet.
Currently, the extension has near complete support for syntax highlighting, barring a few minor issues. The rest are planned features, but as this is a pet project that I pick up in my spare time, it's unclear when they will be available.

**Comment by dustinlacewell** [comment]
OK FYI the readme says "debugging" which might distract some people's time.
